'use strict'
let chessmaster = require('./chessmaster3000.js');

let expectedOutput = {
  'input1.fen': [
    {piece: 'p', fromRank: 6, fromFile: 0, toRank: 5, toFile: 0},
    {piece: 'p', fromRank: 6, fromFile: 1, toRank: 5, toFile: 1},
    {piece: 'p', fromRank: 6, fromFile: 2, toRank: 5, toFile: 2},
    {piece: 'p', fromRank: 6, fromFile: 3, toRank: 5, toFile: 3},
    {piece: 'p', fromRank: 6, fromFile: 4, toRank: 5, toFile: 4},
    {piece: 'p', fromRank: 6, fromFile: 5, toRank: 5, toFile: 5},
    {piece: 'p', fromRank: 6, fromFile: 6, toRank: 5, toFile: 6},
    {piece: 'p', fromRank: 6, fromFile: 7, toRank: 5, toFile: 7},
    {piece: 'p', fromRank: 6, fromFile: 0, toRank: 4, toFile: 0},
    {piece: 'p', fromRank: 6, fromFile: 1, toRank: 4, toFile: 1},
    {piece: 'p', fromRank: 6, fromFile: 2, toRank: 4, toFile: 2},
    {piece: 'p', fromRank: 6, fromFile: 3, toRank: 4, toFile: 3},
    {piece: 'p', fromRank: 6, fromFile: 4, toRank: 4, toFile: 4},
    {piece: 'p', fromRank: 6, fromFile: 5, toRank: 4, toFile: 5},
    {piece: 'p', fromRank: 6, fromFile: 6, toRank: 4, toFile: 6},
    {piece: 'p', fromRank: 6, fromFile: 7, toRank: 4, toFile: 7},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 5, toFile: 0},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 5, toFile: 2},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 5, toFile: 5},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 5, toFile: 7},
  ],
  'input2.fen': [
    {piece: 'p', fromRank: 1, fromFile: 0, toRank: 2, toFile: 0},
    {piece: 'p', fromRank: 1, fromFile: 1, toRank: 2, toFile: 1},
    {piece: 'p', fromRank: 1, fromFile: 2, toRank: 2, toFile: 2},
    {piece: 'p', fromRank: 1, fromFile: 3, toRank: 2, toFile: 3},
    {piece: 'p', fromRank: 1, fromFile: 4, toRank: 2, toFile: 4},
    {piece: 'p', fromRank: 1, fromFile: 5, toRank: 2, toFile: 5},
    {piece: 'p', fromRank: 1, fromFile: 6, toRank: 2, toFile: 6},
    {piece: 'p', fromRank: 1, fromFile: 7, toRank: 2, toFile: 7},
    {piece: 'p', fromRank: 1, fromFile: 0, toRank: 3, toFile: 0},
    {piece: 'p', fromRank: 1, fromFile: 1, toRank: 3, toFile: 1},
    {piece: 'p', fromRank: 1, fromFile: 2, toRank: 3, toFile: 2},
    {piece: 'p', fromRank: 1, fromFile: 3, toRank: 3, toFile: 3},
    {piece: 'p', fromRank: 1, fromFile: 4, toRank: 3, toFile: 4},
    {piece: 'p', fromRank: 1, fromFile: 5, toRank: 3, toFile: 5},
    {piece: 'p', fromRank: 1, fromFile: 6, toRank: 3, toFile: 6},
    {piece: 'p', fromRank: 1, fromFile: 7, toRank: 3, toFile: 7},
    {piece: 'n', fromRank: 0, fromFile: 1, toRank: 2, toFile: 0},
    {piece: 'n', fromRank: 0, fromFile: 1, toRank: 2, toFile: 2},
    {piece: 'n', fromRank: 0, fromFile: 6, toRank: 2, toFile: 5},
    {piece: 'n', fromRank: 0, fromFile: 6, toRank: 2, toFile: 7},
  ],
  'input3.fen': [
    {piece: 'p', fromRank: 6, fromFile: 0, toRank: 5, toFile: 0},
    {piece: 'p', fromRank: 6, fromFile: 1, toRank: 5, toFile: 1},
    {piece: 'p', fromRank: 6, fromFile: 2, toRank: 5, toFile: 2},
    {piece: 'p', fromRank: 6, fromFile: 3, toRank: 5, toFile: 3},
    {piece: 'p', fromRank: 4, fromFile: 4, toRank: 3, toFile: 4},
    {piece: 'p', fromRank: 6, fromFile: 5, toRank: 5, toFile: 5},
    {piece: 'p', fromRank: 6, fromFile: 6, toRank: 5, toFile: 6},
    {piece: 'p', fromRank: 6, fromFile: 7, toRank: 5, toFile: 7},
    {piece: 'p', fromRank: 6, fromFile: 0, toRank: 4, toFile: 0},
    {piece: 'p', fromRank: 6, fromFile: 1, toRank: 4, toFile: 1},
    {piece: 'p', fromRank: 6, fromFile: 2, toRank: 4, toFile: 2},
    {piece: 'p', fromRank: 6, fromFile: 3, toRank: 4, toFile: 3},
    {piece: 'p', fromRank: 6, fromFile: 5, toRank: 4, toFile: 5},
    {piece: 'p', fromRank: 6, fromFile: 6, toRank: 4, toFile: 6},
    {piece: 'p', fromRank: 6, fromFile: 7, toRank: 4, toFile: 7},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 5, toFile: 0},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 5, toFile: 2},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 5, toFile: 5},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 5, toFile: 7},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 6, toFile: 4},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 6, toFile: 4},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 5, toFile: 3},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 4, toFile: 2},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 3, toFile: 1},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 2, toFile: 0},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 6, toFile: 4},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 6, toFile: 4},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 5, toFile: 5},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 4, toFile: 6},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 3, toFile: 7},
  ],
  'input4.fen': [
    {piece: 'p', fromRank: 1, fromFile: 0, toRank: 2, toFile: 0},
    {piece: 'p', fromRank: 1, fromFile: 1, toRank: 2, toFile: 1},
    {piece: 'p', fromRank: 3, fromFile: 2, toRank: 4, toFile: 2},
    {piece: 'p', fromRank: 1, fromFile: 3, toRank: 2, toFile: 3},
    {piece: 'p', fromRank: 1, fromFile: 4, toRank: 2, toFile: 4},
    {piece: 'p', fromRank: 1, fromFile: 5, toRank: 2, toFile: 5},
    {piece: 'p', fromRank: 1, fromFile: 6, toRank: 2, toFile: 6},
    {piece: 'p', fromRank: 1, fromFile: 7, toRank: 2, toFile: 7},
    {piece: 'p', fromRank: 1, fromFile: 0, toRank: 3, toFile: 0},
    {piece: 'p', fromRank: 1, fromFile: 1, toRank: 3, toFile: 1},
    {piece: 'p', fromRank: 1, fromFile: 3, toRank: 3, toFile: 3},
    {piece: 'p', fromRank: 1, fromFile: 4, toRank: 3, toFile: 4},
    {piece: 'p', fromRank: 1, fromFile: 5, toRank: 3, toFile: 5},
    {piece: 'p', fromRank: 1, fromFile: 6, toRank: 3, toFile: 6},
    {piece: 'p', fromRank: 1, fromFile: 7, toRank: 3, toFile: 7},
    {piece: 'n', fromRank: 0, fromFile: 1, toRank: 2, toFile: 0},
    {piece: 'n', fromRank: 0, fromFile: 1, toRank: 2, toFile: 2},
    {piece: 'n', fromRank: 0, fromFile: 6, toRank: 2, toFile: 5},
    {piece: 'n', fromRank: 0, fromFile: 6, toRank: 2, toFile: 7},
    {piece: 'q', fromRank: 0, fromFile: 3, toRank: 1, toFile: 2},
    {piece: 'q', fromRank: 0, fromFile: 3, toRank: 2, toFile: 1},
    {piece: 'q', fromRank: 0, fromFile: 3, toRank: 3, toFile: 0},
  ],
  'input5.fen': [
    {piece: 'p', fromRank: 4, fromFile: 1, toRank: 5, toFile: 1},
    {piece: 'p', fromRank: 4, fromFile: 1, toRank: 5, toFile: 0},
  ],
  'input6.fen': [
    {piece: 'p', fromRank: 6, fromFile: 0, toRank: 5, toFile: 0},
    {piece: 'p', fromRank: 6, fromFile: 1, toRank: 5, toFile: 1},
    {piece: 'p', fromRank: 6, fromFile: 2, toRank: 5, toFile: 2},
    {piece: 'p', fromRank: 6, fromFile: 3, toRank: 5, toFile: 3},
    {piece: 'p', fromRank: 6, fromFile: 4, toRank: 5, toFile: 4},
    {piece: 'p', fromRank: 6, fromFile: 5, toRank: 5, toFile: 5},
    {piece: 'p', fromRank: 6, fromFile: 6, toRank: 5, toFile: 6},
    {piece: 'p', fromRank: 6, fromFile: 7, toRank: 5, toFile: 7},
    {piece: 'p', fromRank: 6, fromFile: 0, toRank: 4, toFile: 0},
    {piece: 'p', fromRank: 6, fromFile: 1, toRank: 4, toFile: 1},
    {piece: 'p', fromRank: 6, fromFile: 2, toRank: 4, toFile: 2},
    {piece: 'p', fromRank: 6, fromFile: 3, toRank: 4, toFile: 3},
    {piece: 'p', fromRank: 6, fromFile: 4, toRank: 4, toFile: 4},
    {piece: 'p', fromRank: 6, fromFile: 5, toRank: 4, toFile: 5},
    {piece: 'p', fromRank: 6, fromFile: 6, toRank: 4, toFile: 6},
    {piece: 'p', fromRank: 6, fromFile: 7, toRank: 4, toFile: 7},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 7, toFile: 1},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 7, toFile: 2},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 7, toFile: 3},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 7, toFile: 6},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 7, toFile: 5},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 7, toFile: 3},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 7, toFile: 5},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 7, toFile: 6, castle: true},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 7, toFile: 2, castle: true},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 7, toFile: 5, castle: true},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 7, toFile: 3, castle: true},
  ],
  'input7.fen': [
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 6, toFile: 0},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 5, toFile: 0},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 4, toFile: 0},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 3, toFile: 0},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 2, toFile: 0},
    {piece: 'r', fromRank: 7, fromFile: 0, toRank: 1, toFile: 0},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 5, toFile: 2},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 5, toFile: 0},
    {piece: 'n', fromRank: 7, fromFile: 1, toRank: 6, toFile: 3},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 6, toFile: 3},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 5, toFile: 4},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 4, toFile: 5},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 3, toFile: 6},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 2, toFile: 7},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 6, toFile: 1},
    {piece: 'b', fromRank: 7, fromFile: 2, toRank: 5, toFile: 0},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 6, toFile: 3},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 5, toFile: 3},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 4, toFile: 3},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 3, toFile: 3},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 2, toFile: 3},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 1, toFile: 3},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 6, toFile: 4},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 5, toFile: 5},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 4, toFile: 6},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 3, toFile: 7},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 6, toFile: 2},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 5, toFile: 1},
    {piece: 'q', fromRank: 7, fromFile: 3, toRank: 4, toFile: 0},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 6, toFile: 3},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 6, toFile: 4},
    {piece: 'k', fromRank: 7, fromFile: 4, toRank: 6, toFile: 5},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 6, toFile: 6},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 5, toFile: 7},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 6, toFile: 4},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 5, toFile: 3},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 4, toFile: 2},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 3, toFile: 1},
    {piece: 'b', fromRank: 7, fromFile: 5, toRank: 2, toFile: 0},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 5, toFile: 5},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 5, toFile: 7},
    {piece: 'n', fromRank: 7, fromFile: 6, toRank: 6, toFile: 4},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 6, toFile: 7},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 5, toFile: 7},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 4, toFile: 7},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 3, toFile: 7},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 2, toFile: 7},
    {piece: 'r', fromRank: 7, fromFile: 7, toRank: 1, toFile: 7},
  ],
  'input8.fen': [
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 5, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 6, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 7, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 3, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 2, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 1, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 0, toFile: 3},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 4},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 5},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 6},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 7},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 2},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 1},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 4, toFile: 0},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 5, toFile: 4},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 6, toFile: 5},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 7, toFile: 6},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 3, toFile: 4},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 2, toFile: 5},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 1, toFile: 6},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 0, toFile: 7},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 5, toFile: 2},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 6, toFile: 1},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 7, toFile: 0},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 3, toFile: 2},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 2, toFile: 1},
    {piece: 'q', fromRank: 4, fromFile: 3, toRank: 1, toFile: 0},
  ]
}

let compare = function(a, b) {
  let aStr = ''+a.castle+a.piece+a.fromRank+a.fromFile+a.toRank+a.toFile;
  let bStr = ''+b.castle+b.piece+b.fromRank+b.fromFile+b.toRank+b.toFile;
  return aStr.localeCompare(bStr);
}

Object.keys(expectedOutput).forEach((filename) => {
  let state = chessmaster.importFile(filename);
  let moveOptions = chessmaster.getOptionsForPlayer(state, state.playerTurn);
  let actual = JSON.stringify(moveOptions.sort(compare));
  let expected = JSON.stringify(expectedOutput[filename].sort(compare));
  if(actual !== expected) {
    console.log('FAILED', filename, '\n', actual.length, '\n', expected.length);
  } else {
    console.log('PASSED', filename);
  }
});
